[path]
master_log_file = "data/debug/logs/master.log"
prog_log_file = "data/debug/logs/prog.log"
data_header = "data/"
test_log_file = "data/test_log.csv"
path_data = "D:\\nirram\\data\\MPW_Test\\"

[NIDigital]
deviceID = ["PXI6571Slot4", "PXI6571Slot5", "PXI6570Slot8"]

pinmap = [
    "settings/pinmap/CSA_Slot4.pinmap",
    "settings/pinmap/CSA_Slot5.pinmap",  
    "settings/pinmap/MPW_CSA_2D.pinmap"
    ]

specs = ["settings/Stanford_3DSoC/MPW_3DSoC.specs"]

patterns = [
    "settings/patterns/CSA_Slot4.digipat",
    "settings/patterns/CSA_Slot5.digipat",
    "settings/patterns/MPW_CSA_2D.digipat"
]

pulse_pingroups = ["BL","SL", "WL","PWR"]

power_pins = ["VDD", "VSA","V_BRD+","V_BRD-"]
clock_pins = ["SA_CLK"]

[sources]

# Defining power pins
[sources.power_pins]
VDD = 1.8
VSS = 0
VSA = 1.8

# Defining the setup for the test
[sources.setup_pins]
MUX_SEL_CONV_CLK = 0
MUX_SEL_WT  = 0
SA_CLK_EXT = 0
WT_SEL_EXT = 0

[pins]
# Defining clock pins
[pins.clk_pins]
SA_CLK = 0

# Defining input pins for the test
[pins.input_pins]
VREAD = 0.3
SA_EN = 5
WL_UNSEL = 0
WL = 0.3
COL_SEL = 5

# Defining output pins for the test
[pins.output_pins]
SA_RDY = [0,0]
DO = [0,0]

# Defining WL Pins
[pins.WL]
WL_IN = [
    "WL_IN_0",
    "WL_IN_1",
    "WL_IN_2",
    "WL_IN_3",
    "WL_IN_4",
    "WL_IN_5",
    "WL_IN_6",
    "WL_IN_7",
    "WL_IN_8",
    "WL_IN_9",
    "WL_IN_10",
    "WL_IN_11",
    "WL_IN_12",
    "WL_IN_13",
    "WL_IN_14",
    "WL_IN_15",
    "WL_IN_16",
    "WL_IN_17",
    "WL_IN_18",
    "WL_IN_19",
    "WL_IN_20",
    "WL_IN_21",
    "WL_IN_22",
    "WL_IN_23",
    "WL_IN_24",
    ]
WL = [
        "WL_0",
        "WL_1",
        "WL_2",
        "WL_3",
        "WL_4",
        "WL_5",
        "WL_6",
        "WL_7",
        "WL_8",
        "WL_9",
        "WL_10",
        "WL_11",
        "WL_12",
        "WL_13",
        "WL_14",
        "WL_15",
        "WL_16",
        "WL_17",
        "WL_18",
        "WL_19",
        "WL_20",
        "WL_21",
        "WL_22",
        "WL_23",
        "WL_24",
        "WL_25",
        "WL_26",
        "WL_28",
        "WL_29",
        "WL_30",
        "WL_31",
        "WL_32",
        "WL_33",
        "WL_34",
        "WL_35",
        "WL_36",
        "WL_37",
        "WL_38",
        "WL_39",
        "WL_40",
        "WL_41",
        "WL_42",
        "WL_43",
        "WL_44",
        "WL_45",
        "WL_46",
        "WL_47",
        "WL_48",
        "WL_49",
        "WL_50",
        "WL_51",
        "WL_52",
        "WL_53",
        "WL_54",
        "WL_55",
        "WL_56",
        "WL_57",
        "WL_58",
        "WL_59",
        "WL_60",
        "WL_61",
        "WL_62",
        "WL_63",
        "WL_64",
        "WL_65",
        "WL_66",
        "WL_67",
        "WL_68",
        "WL_69",
        "WL_70",
        "WL_71",
        "WL_72",
        "WL_73",
        "WL_74",
        "WL_75",
        "WL_76",
        "WL_77",
        "WL_78",
        "WL_79",
        "WL_80",
        "WL_81",
        "WL_82",
        "WL_83",
        "WL_84",
        "WL_85",
        "WL_86",
        "WL_87",
        "WL_88",
        "WL_89",
        "WL_90",
        "WL_91",
        "WL_92",
        "WL_93",
        "WL_94",
        "WL_95",
        "WL_96",
        "WL_97",
        "WL_98",
        "WL_99",
        "WL_100",
        "WL_101",
        "WL_102",
        "WL_103",
        "WL_104",
        "WL_105",
        "WL_106",
        "WL_107",
        "WL_108",
        "WL_109",
        "WL_110",
        "WL_111",
        "WL_112",
        "WL_113",
        "WL_114",
        "WL_115",
        "WL_116",
        "WL_117",
        "WL_118",
        "WL_119",
        "WL_120",
        "WL_121",
        "WL_122",
        "WL_123",
        "WL_124",
        "WL_125",
        "WL_126",
        "WL_127",
]

# Defining BL Pins
[pins.BL]
BL = [
    "BL_0",
    "BL_1",
    "BL_2",
    "BL_3",
    "BL_4",
    "BL_5",
    "BL_6",
    "BL_7",
    "BL_8",
    "BL_9",
    "BL_10",
    "BL_11",
    "BL_12",
    "BL_13",
    "BL_14",
    "BL_15",
    "BL_16",
    "BL_17",
    "BL_18",
    "BL_19",
    "BL_20",
    "BL_21",
    "BL_22",
    "BL_23",
    "BL_24",
    "BL_25",
    "BL_26",
    "BL_27",
    "BL_28",
    "BL_29",
    "BL_30",
    "BL_31",
]

[op]

[op.READ]
mode = "digital"
aperture_time = 0.00005

#2 uA, 32uA, 128uA, 2mA, 32mA
current_limit_range = 128e-6
relaxation_cycles = 100
settling_time = 0.0001
shunt_res_value = 0

[op.READ.NMOS]
VWL = 2
VBL = 0.3
VSL = 0
VWL_UNSEL_OFFSET = 0
VB = 0

[op.READ.PMOS]
