[path]
master_log_file = "data/debug/logs/master.log"
prog_log_file = "data/debug/logs/prog.log"
data_header = "data/"
test_log_file = "data/test_log.csv"
path_data = "D:\\nirram\\data\\MPW_Test\\"

[NIDigital]
deviceID = ["PXI6571Slot4", "PXI6571Slot5", "PXI6570Slot8"]
pinmap = ["settings/pinmap/MPW_Peripheral_3D_BL.pinmap","settings/pinmap/MPW_Peripheral_3D_SL.pinmap",  "settings/pinmap/MPW_Peripheral_3D_WL.pinmap"]
specs = ["settings/Stanford_3DSoC/MPW_3DSoC.specs"]

timing = [
  "settings/timing/MPW_Peripheral_3D_BL.digitiming",
  "settings/timing/MPW_Peripheral_3D_SL.digitiming",
  "settings/timing/MPW_Peripheral_3D_WL.digitiming"
]
levels = [
    "settings/levels/MPW_Peripheral_3D_BL.digilevels",
    "settings/levels/MPW_Peripheral_3D_SL.digilevels",
    "settings/levels/MPW_Peripheral_3D_WL.digilevels"
]
# Each pattern is defined by an array of each session pattern
# So a pattern for direct write is defined by the array of 
# the BLSL session pattern and the WL session pattern for direct write
patterns = [
    "settings/patterns/3D/MPW_Peripheral_Conv_3D_BL.digipat",
    "settings/patterns/3D/MPW_Peripheral_Conv_3D_SL.digipat",
    "settings/patterns/3D/MPW_Peripheral_Conv_3D_WL.digipat"
]

source_waveforms = [
    "settings/waveforms/3D/MPW_Peripheral_Conv_3D_BL.tdms",
    "settings/waveforms/3D/MPW_Peripheral_Conv_3D_SL.tdms",
    "settings/waveforms/3D/MPW_Peripheral_Conv_3D_WL.tdms"
]

source_waveform_names = [
    "Conv_Test_3D_BL",
    "Conv_Test_3D_SL",
    "Conv_Test_3D_WL"
]
capture_waveforms = [
    "Conv_Test_BL_OFMAP",
    "NO WAVEFORM",
    "NO WAVEFORM",
]

capture_waveform_names = [
    "Conv_Test_BL_OFMAP",
    "NO WAVEFORM",
    "NO WAVEFORM",
]

capture_pins = [
    ["OFMAP_0","OFMAP_1","OFMAP_2","OFMAP_3","OFMAP_4","OFMAP_5","OFMAP_6","OFMAP_7","OFMAP_8","OFMAP_9","OFMAP_10","OFMAP_11","OFMAP_12","OFMAP_13","OFMAP_14","OFMAP_15","OFMAP_16","OFMAP_17","OFMAP_18","OFMAP_19","OFMAP_20","OFMAP_21","OFMAP_22","OFMAP_23"],
    [],
    []
]

sample_length = 98

[NISwitch]
deviceID = ["PXI2571Slot2", "PXI2571Slot3"]

[TIMING]
direct = 2e-5
CSA = 2e-5

[device]
pins = [["BL","PE_EN", "OFMAP"],
        ["SL","IFMAP", "IFMAP_EN", "EXT_WT","WEIGHT_EN","WEIGHT_SHIFT","WT_SEL_EXT","RST_N","PSUM_SLC","MUX_SEL_CONV_CLK","MUX_SEL_WT"],
        ["WL", "ACCUM_EN","SA_CLK","SA_CLK_EXT"]
        ]

# VHDCI A
BL = ["BL_0","BL_1","BL_2","BL_3","BL_29","BL_30","BL_31"]
PE_EN = "PE_EN"
OFMAP = ["OFMAP_0",
        "OFMAP_1",
        "OFMAP_2",
        "OFMAP_3",
        "OFMAP_4",
        "OFMAP_5",
        "OFMAP_6",
        "OFMAP_7", 
        "OFMAP_8", 
        "OFMAP_9", 
        "OFMAP_10", 
        "OFMAP_11", 
        "OFMAP_12", 
        "OFMAP_13", 
        "OFMAP_14", 
        "OFMAP_15", 
        "OFMAP_16", 
        "OFMAP_17", 
        "OFMAP_18", 
        "OFMAP_19", 
        "OFMAP_20", 
        "OFMAP_21",
        "OFMAP_22", 
        "OFMAP_23",
]

#VHDCI B
SL = ["SL_0","SL_1","SL_2","SL_3","SL_29","SL_30","SL_31"]
IFMAP = ["IFMAP_0",
        "IFMAP_1",
        "IFMAP_2",
        "IFMAP_3",
        "IFMAP_4",
        "IFMAP_5",
        "IFMAP_6",
        "IFMAP_7",
]
MUX_SEL_WT = "MUX_SEL_WT"
IFMAP_EN = "IFMAP_EN"
EXT_WT = ["EXT_WT_0", "EXT_WT_1", "EXT_WT_2","EXT_WT_3","EXT_WT_4","EXT_WT_5","EXT_WT_6","EXT_WT_7"]
WEIGHT_EN = "WEIGHT_EN"
WEIGHT_SHIFT = "WEIGHT_SHIFT"
WT_SEL_EXT = "WT_SEL_EXT"
RST_N = "RST_N"
PSUM_SLC = "PSUM_SLC"
MUX_SEL_CONV_CLK="MUX_SEL_CONV_CLK"

#VHDCI C
WL = ["WL_IN_0","WL_IN_21","WL_IN_22","WL_IN_23","WL_UNSEL"]
ACCUM_EN = "ACCUM_EN"
SA_CLK = "SA_CLK"
SA_CLK_EXT = "SA_CLK_EXT"

[voltages]
vih = 1.8
vil = 0.0
voh = 1.8
vol = 0.0

[other_voltages.OFMAP]
vih = 0.7
vil = 0.3
voh = 0.7
vol = 0.3
