[path]
master_log_file = "data/debug/logs/master.log"
prog_log_file = "data/debug/logs/prog.log"
data_header = "data/"
test_log_file = "data/test_log.csv"
path_data = "D:\\nirram\\data\\MPW_Test\\"

[NIDigital]
deviceID = ["PXI6571Slot4", "PXI6571Slot5", "PXI6570Slot8"]
pinmap = ["settings/pinmap/MPW_Peripheral_2D_BL.pinmap","settings/pinmap/MPW_Peripheral_2D_SL.pinmap",  "settings/pinmap/MPW_Peripheral_2D_WL.pinmap"]
specs = ["settings/Stanford_3DSoC/MPW_3DSoC.specs"]

timing = [
  "settings/timing/MPW_Peripheral_CSA_2D_BL.digitiming",
  "settings/timing/MPW_Peripheral_CSA_2D_SL.digitiming",
  "settings/timing/MPW_Peripheral_CSA_2D_WL.digitiming"
]
levels = [
    "settings/levels/MPW_Peripheral_CSA_2D_BL.digilevels",
    "settings/levels/MPW_Peripheral_CSA_2D_SL.digilevels",
    "settings/levels/MPW_Peripheral_CSA_2D_WL.digilevels"
]
# Each pattern is defined by an array of each session pattern
# So a pattern for direct write is defined by the array of 
# the BLSL session pattern and the WL session pattern for direct write
patterns = [
    "settings/patterns/2D/MPW_Peripheral_CSA_2D_BL.digipat",
    "settings/patterns/2D/MPW_Peripheral_CSA_2D_SL.digipat",
    "settings/patterns/2D/MPW_Peripheral_CSA_2D_WL.digipat"
]

source_waveforms = [
    "settings/waveforms/2D/MPW_Peripheral_CSA_2D_BL.tdms",
    "settings/waveforms/2D/MPW_Peripheral_CSA_2D_SL.tdms",
    "settings/waveforms/2D/MPW_Peripheral_CSA_2D_WL.tdms"
]

source_waveform_names = [
    "CSA_Test_2D_BL",
    "CSA_Test_2D_SL",
    "CSA_Test_2D_WL"
]
capture_waveforms = [
    "NO_WAVEFORM",
    "NO_WAVEFORM",
    "MPW_Peripheral_CSA_2D_WL.digicapture",
    
]

capture_waveform_names = [
    "NO_WAVEFORM",
    "NO_WAVEFORM",
    "CSA_Test_WL_DO_SA_RDY",
]

capture_pins = [
    [],
    [],
    ["DO_1","DO_0","SA_RDY_1","SA_RDY_0"]
]

sample_length = 73

[NISwitch]
deviceID = ["PXI2571Slot2", "PXI2571Slot3"]

[TIMING]
direct = 2e-6
CSA = 2e-6

[device]
pins = [["BL"],
        ["SL", "WT_SEL_EXT", "MUX_SEL_CONV_CLK","IFMAP_EN","PSUM_SLC","WEIGHT_EN","WEIGHT_SHIFT","MUX_SEL_WT","RST_N"],
        ["VREAD", "COLSEL", "SA_EN", "RMUX_EN","SA_CLK","SA_CLK_EXT","DIR_PERIPH_SEL","DO_SA_RDY"]
        ]

BL = ["BL_3", "BL_2","BL_1","BL_0"]

SL = ["SL_3", "SL_2","SL_1","SL_0"]
WT_SEL_EXT = "WT_SEL_EXT"
MUX_SEL_CONV_CLK = "MUX_SEL_CONV_CLK"
IFMAP_EN = "IFMAP_EN"
PSUM_SLC = "PSUM_SLC"
WEIGHT_EN = "WEIGHT_EN"
WEIGHT_SHIFT = "WEIGHT_SHIFT"
MUX_SEL_WT = "MUX_SEL_WT"
RST_N = "RST_N"

VREAD = "VREAD"
COLSEL = [
    "COL_SEL_15",
    "COL_SEL_14",
    "COL_SEL_13",
    "COL_SEL_12",
    "COL_SEL_11",
    "COL_SEL_10",
    "COL_SEL_9",
    "COL_SEL_8",
    "COL_SEL_7",
    "COL_SEL_6",
    "COL_SEL_5",
    "COL_SEL_4",
    "COL_SEL_3",
    "COL_SEL_2",
    "COL_SEL_1",
    "COL_SEL_0",
]
SA_EN = "SA_EN"
RMUX_EN = "RMUX_EN"
SA_CLK = "SA_CLK"
SA_CLK_EXT = "SA_CLK_EXT"
DIR_PERIPH_SEL = "DIR_PERIPH_SEL"
DO_SA_RDY = ["DO_1","DO_0","SA_RDY_1","SA_RDY_0"]


[voltages]
vih = 1.8
vil = 0.0
voh = 1.8
vol = 0.0

[other_voltages]
[other_voltages.RMUX_EN]
vih = 5.0
vil = 0.0
voh = 5.0
vol = 0.0

[other_voltages.VREAD]
vih = 0.3
vil = 0.0
voh = 0.3
vol = 0.0

[other_voltages.SARDY_DO]
vih = 1.5
vil = 0.0
voh = 1.5
vol = 0.0